#%RAML 0.8
title: FEES/FINES HISTORY
version: v1
baseUri: http://github.com/org/folio/mod-feefines

documentation:
  - title: mod-feefines FEES/FINES HISTORY API
    content: This documents the API calls that can be made to query and manage feefinehistory of the system

schemas:
  - feefinehistorydata: !include schemas/feefinehistorydata.json
  - feefinehistorydataCollection: !include schemas/feefinehistorydataCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error: !include ../raml-util/schemas/error.schema
  - parameters: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - orderable: !include ../raml-util/traits/orderable.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml
  - post-empty-body: !include ../raml-util/rtypes/post-empty-body.raml

/feefinehistory:
  type:
    collection:
      exampleCollection: !include examples/feefinehistory_collection.sample
      exampleItem: !include examples/feefinehistory.sample
      schemaCollection: feefinehistorydataCollection
      schemaItem: feefinehistorydata
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of feefinehistorys
  post:
#    is: [validate]
    description: Create a feefinehistory
  /{feefinehistoryId}:
    type:
      collection-item:
        exampleItem: !include examples/feefinehistory.sample
        schema: feefinehistorydata
    get:
      description: Get a single feefinehistory

