#%RAML 1.0 ResourceType
description: "Performs an action on an account"
post:
  is: [validate]
  description: "Perform action"
  body:
    application/json:
      type: actionRequest
  responses:
    201:
      description: "Action was performed successfully"
      body:
        application/json:
          type: actionSuccessResponse
    404:
      description: "Fee/fine was not found"
      body:
        text/plain:
          example: "Fee/fine was not found"
    422:
      description: "Action is not allowed"
      body:
        application/json:
          type: actionFailureResponse
    500:
      description: "Internal server error"
      body:
        text/plain:
          example: "Internal server error, please contact administrator"