description: "Checks if the requested action is allowed"
post:
  description: "Checks if an action is allowed"
  body:
    application/json:
      type: checkActionRequest
  responses:
    200:
      description: "Action is allowed"
      body:
        application/json:
          type: checkActionResponse
    404:
      description: "Fee/fine was not found"
      body:
        text/plain:
          example: "Fee/fine was not found"
    422:
      description: "Action is not allowed"
      body:
        application/json:
          type: checkActionResponse
    500:
      description: "Internal server error"
      body:
        text/plain:
          example: "Internal server error"