#%RAML 0.8
title: Accounts
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Accounts API
    content: This documents the API calls that can be made to query and manage feefine of the system

schemas:
  - accountdata: !include schemas/accountdata.json
  - accountdataCollection: !include schemas/accountdataCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error: !include ../raml-util/schemas/error.schema
  - parameters: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - orderable: !include ../raml-util/traits/orderable.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml
  - post-empty-body: !include ../raml-util/rtypes/post-empty-body.raml

/accounts:
  type:
    collection:
      exampleCollection: !include examples/account_collection.sample
      exampleItem: !include examples/account.sample
      schemaCollection: accountdataCollection
      schemaItem: accountdata
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of accounts
  post:
#    is: [validate]
    description: Create a account
  /{accountId}:
    type:
      collection-item:
        exampleItem: !include examples/account.sample
        schema: accountdata
    get:
      description: Get a single account

