#%RAML 1.0
title: Accounts
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Accounts API
    content: This documents the API calls that can be made to query and manage feefine of the system

types:
  account: !include accountdata.json
  accountdataCollection: !include accountdataCollection.json
  errors: !include raml-util/schemas/errors.schema
  patronNotice: !include patronNotice.json
  checkActionRequest: !include checkActionRequest.json
  checkActionResponse: !include checkActionResponse.json
  actionRequest: !include actionRequest.json
  actionResponse: !include actionResponse.json

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml
  facets: !include raml-util/traits/facets.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/accounts:
  type:
    collection:
      exampleCollection: !include examples/account_collection.sample
      exampleItem: !include examples/account.sample
      schemaCollection: accountdataCollection
      schemaItem: account
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable,
      facets
    ]
    description: "Return a list of accounts"
  post:
    is: [validate]
    description: "Create a account"
  /{accountId}:
    type:
      collection-item:
        exampleItem: !include examples/account.sample
        schema: account
    get:
      description: Get a single account
    /check-pay:
      post:
        description: Checks if payment is valid
        body:
          application/json:
            type: checkActionRequest
        responses:
          200:
            description: "Payment is allowed"
            body:
              application/json:
                type: checkActionResponse
          404:
            description: "Account was not found"
            body:
              text/plain:
                example: "Account was not found"
          422:
            description: "Payment is not allowed"
            body:
              application/json:
                type: checkActionResponse
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
    /check-waive:
      post:
        description: Checks if waive is valid
        body:
          application/json:
            type: checkActionRequest
        responses:
          200:
            description: "Waiver is allowed"
            body:
              application/json:
                type: checkActionResponse
          404:
            description: "Account was not found"
            body:
              text/plain:
                example: "Account was not found"
          422:
            description: "Waiver is not allowed"
            body:
              application/json:
                type: checkActionResponse
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
    /pay:
      post:
        is: [validate]
        description: "Makes payment"
        body:
          application/json:
            type: actionRequest
        responses:
          201:
            description: "Payment was made successfully"
            body:
              application/json:
                type: actionResponse
          404:
            description: "Account was not found"
            body:
              text/plain:
                example: "Account was not found"
          422:
            description: "Action is not allowed"
            body:
              application/json:
                type: actionResponse
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error, please contact administrator"