#%RAML 0.8
title: Fee Fine Actions
version: v1
baseUri: http://github.com/org/folio/mod-feefines

documentation:
  - title: mod-feefines API
    content: This documents the API calls that can be made to query and manage feefine of the system

schemas:
  - feefineactiondata: !include schemas/feefineactiondata.json
  - feefineactiondataCollection: !include schemas/feefineactiondataCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error: !include ../raml-util/schemas/error.schema
  - parameters: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - orderable: !include ../raml-util/traits/orderable.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml
  - post-empty-body: !include ../raml-util/rtypes/post-empty-body.raml

/feefineactions:
  type:
    collection:
      exampleCollection: !include examples/feefineaction_collection.sample
      exampleItem: !include examples/feefineaction.sample
      schemaCollection: feefineactiondataCollection
      schemaItem: feefineactiondata
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of feefineactions
  post:
#    is: [validate]
    description: Create a feefineaction
  /{feefineactionId}:
    type:
      collection-item:
        exampleItem: !include examples/feefineaction.sample
        schema: feefineactiondata
    get:
      description: Get a single feefineaction

