#%RAML 1.0
title: Feefines
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Feefines API
    content: This documents the API calls that can be made to query and manage feefine of the system

types:
  feefine: !include feefinedata.json
  feefinedataCollection: !include feefinedataCollection.json
  errors: !include raml-util/schemas/errors.schema
  error.schema: !include raml-util/schemas/error.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml
  facets: !include raml-util/traits/facets.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/feefines:
  type:
    collection:
      exampleCollection: !include examples/feefine_collection.sample
      exampleItem: !include examples/feefine.sample
      schemaCollection: feefinedataCollection
      schemaItem: feefine
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable,
      facets
    ]
    description: Return a list of feefines
  post:
#    is: [validate]
    description: Create a feefine
  /{feefineId}:
    type:
      collection-item:
        exampleItem: !include examples/feefine.sample
        schema: feefine
    get:
      description: Get a single feefine
