#%RAML 1.0
title: Fee/fine reports
version: v2.2
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Fee/fine reports API
    content: This documents the API calls for loading fee/fine reports

types:
  user: !include user.json
  userGroup: !include usergroup.json
  servicePoint: !include servicepoint.json
  loan: !include loan.json
  loanPolicy: !include loan-policy.json
  refundReport: !include reports/refundReport.json
  refundReportRequest: !include reports/refundReportRequest.json
  cashDrawerReconciliationReport: !include reports/cashDrawerReconciliationReport.json
  cashDrawerReconciliationReportRequest: !include reports/cashDrawerReconciliationReportRequest.json
  cashDrawerReconciliationReportSources: !include reports/cashDrawerReconciliationReportSources.json
  cashDrawerReconciliationReportSourcesRequest: !include reports/cashDrawerReconciliationReportSourcesRequest.json
  financialTransactionsDetailReport: !include reports/financialTransactionsDetailReport.json
  financialTransactionsDetailReportRequest: !include reports/financialTransactionsDetailReportRequest.json
  kvConfigurations: !include kv-configurations.json
  kvConfiguration: !include kv-configuration.json
  errors: !include raml-util/schemas/errors.schema
  error.schema: !include raml-util/schemas/error.schema

traits:
  validate: !include raml-util/traits/validation.raml

/feefine-reports:
  /refund:
    post:
      is: [validate]
      description: "Return data for a refund report"
      body:
        application/json:
          schema: refundReportRequest
          example: !include examples/refundReportRequest.sample
      responses:
        200:
          body:
            application/json:
              schema: refundReport
              example: !include examples/refundReport.sample
        422:
          description: "Unprocessable entity"
          body:
            text/plain:
              example: "Invalid startDate or endDate parameter"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error"
  /cash-drawer-reconciliation:
    post:
      is: [validate]
      description: "Return data for a refund cash drawer reconciliation report"
      body:
        application/json:
          schema: cashDrawerReconciliationReportRequest
          example: !include examples/cashDrawerReconciliationReportRequest.sample
      responses:
        200:
          body:
            application/json:
              schema: cashDrawerReconciliationReport
              example: !include examples/cashDrawerReconciliationReport.sample
        422:
          description: "Unprocessable entity"
          body:
            text/plain:
              example: "Invalid startDate or endDate parameter"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error"
    /sources:
      post:
        is: [validate]
        description: "Return list of sources for a refund cash drawer reconciliation report"
        body:
          application/json:
            schema: cashDrawerReconciliationReportSourcesRequest
            example: !include examples/cashDrawerReconciliationReportSourcesRequest.sample
        responses:
          200:
            body:
              application/json:
                schema: cashDrawerReconciliationReportSources
                example: !include examples/cashDrawerReconciliationReportSources.sample
          422:
            description: "Unprocessable entity"
            body:
              text/plain:
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "Internal server error"
  /financial-transactions-detail:
      post:
        is: [validate]
        description: "Return data for a financial transactions detail report"
        body:
          application/json:
            schema: financialTransactionsDetailReportRequest
            example: !include examples/financialTransactionsDetailReportRequest.sample
        responses:
          200:
            body:
              application/json:
                schema: financialTransactionsDetailReport
                example: !include examples/financialTransactionsDetailReport.sample
          422:
            description: "Unprocessable entity"
            body:
              text/plain:
                example: "Invalid startDate or endDate parameter"
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              text/plain:
                example: "Internal server error"