#%RAML 1.0
title: Fee Fine Actions
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Fee Fine Actions API
    content: This documents the API calls that can be made to query and manage feefine of the system

annotationTypes: 
  fqm-values:
    type: array

types:
  account: !include accountdata.json
  feefineaction: !include feefineactiondata.json
  feefineactiondataCollection: !include feefineactiondataCollection.json

  materialType: !include inventory/materialtype.json
  item: !include inventory/item.json
  items: !include inventory/items.json
  holdings-record: !include inventory/holdingsrecord.json
  holdings-records: !include inventory/holdingsrecords.json
  instance: !include inventory/instance.json
  location: !include inventory/location.json
  loanType: !include inventory/loantype.json
  user: !include user.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/feefineactions:
  type:
    collection:
      exampleCollection: !include examples/feefineaction_collection.sample
      exampleItem: !include examples/feefineaction.sample
      schemaCollection: feefineactiondataCollection
      schemaItem: feefineaction
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of feefineactions
  post:
    is: [validate]
    description: Create a feefineaction
  /{feefineactionId}:
    type:
      collection-item:
        exampleItem: !include examples/feefineaction.sample
        schema: feefineaction
    get:
      description: Get a single feefineaction

