#%RAML 1.0
title: Templates for Manual Patron Blocks
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Manual Patron Block Templates API
    content: This documents the API calls that can be made to query and manage templates for manualblocks of the system

types:
  manualBlockTemplate: !include manual-block-template.json
  manualBlockTemplateCollection: !include manual-block-templateCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/manual-block-templates:
  type:
    collection:
      exampleCollection: !include examples/manual-block-template_collection.sample
      exampleItem: !include examples/manual-block-template.sample
      schemaCollection: manualBlockTemplateCollection
      schemaItem: manualBlockTemplate
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of manualblock templates
  post:
    is: [validate]
    description: Create a manualblock template
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/manualblock.sample
        schema: manualBlockTemplate
    get:
      description: Get a single manualblock template
    put:
      description: Update a single manualblock template
    delete:
      description: Delete a single manualblock template
