#%RAML 1.0
title: Owners
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Owners API
    content: This documents the API calls that can be made to query and manage owner of the system

types:
  owner: !include ownerdata.json
  ownerdataCollection: !include ownerdataCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/owners:
  type:
    collection:
      exampleCollection: !include examples/owner_collection.sample
      exampleItem: !include examples/owner.sample
      schemaCollection: ownerdataCollection
      schemaItem: owner
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of owners
  post:
    is: [validate]
    description: Create a owner
  /{ownerId}:
    type:
      collection-item:
        exampleItem: !include examples/owner.sample
        schema: owner
    get:
      description: Get a single owner
