#%RAML 1.0
title: Refunds
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Refunds API
    content: This documents the API calls that can be made to query and manage feefine of the system

types:
  refund: !include refunddata.json
  refunddataCollection: !include refunddataCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml
  facets: !include raml-util/traits/facets.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/refunds:
  type:
    collection:
      exampleCollection: !include examples/refund_collection.sample
      exampleItem: !include examples/refund.sample
      schemaCollection: refunddataCollection
      schemaItem: refund
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable,
      facets
    ]
    description: Return a list of refunds
  post:
    is: [validate]
    description: Create a refund
  /{refundId}:
    type:
      collection-item:
        exampleItem: !include examples/refund.sample
        schema: refund
    get:
      description: Get a single refund

