#%RAML 1.0
title: Transfers type
version: v1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: Transfers type API
    content: This documents the API calls that can be made to query and manage feefine of the system

types:
  transfertype: !include transfer-typedata.json
  transfer-typedataCollection: !include transfer-typedataCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-only: !include raml-util/rtypes/get-only.raml
  post-empty-body: !include raml-util/rtypes/post-empty-body.raml

/transfertypes:
  type:
    collection:
      exampleCollection: !include examples/transfer-type_collection.sample
      exampleItem: !include examples/transfer-type.sample
      schemaCollection: transfer-typedataCollection
      schemaItem: transfertype
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "active=true"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Return a list of transfer-types
  post:
#    is: [validate]
    description: Create a transfer-type
  /{transfertypeId}:
    type:
      collection-item:
        exampleItem: !include examples/transfer-type.sample
        schema: transfertype
    get:
      description: Get a single transfer-type
